# Generated by Django 3.2.12 on 2022-03-15 19:01

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery/images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallerys',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'history',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='full name')),
                ('citizenship_district', models.CharField(max_length=255, verbose_name='citizenship district')),
                ('citizenship_number', models.IntegerField(verbose_name='citizenship number')),
                ('voterlist_number', models.IntegerField(verbose_name='voterlist number')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255, verbose_name='gender')),
                ('date_of_birth', models.CharField(max_length=255, verbose_name='date of birth')),
                ('permanent_address', models.CharField(max_length=255, verbose_name='permanent address')),
                ('temporary_address', models.CharField(max_length=255, verbose_name='temporary address')),
                ('marriage_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=255, verbose_name='marriage status')),
                ('number_family_members', models.IntegerField(verbose_name='number of family members')),
                ('education', models.CharField(max_length=255, verbose_name='education')),
                ('caste', models.CharField(max_length=255, verbose_name='caste')),
                ('occupation', models.CharField(max_length=255, verbose_name='occupation')),
                ('conatact_number', models.CharField(max_length=10, verbose_name='contact number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
                ('reason', models.CharField(max_length=255, verbose_name='reason for being member')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'member',
            },
        ),
        migrations.CreateModel(
            name='HistoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='frontend/history/', verbose_name='image')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.history')),
            ],
            options={
                'verbose_name': 'history Translation',
                'db_table': 'frontend_history_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
