# Generated by Django 3.2.12 on 2022-03-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytranslation',
            name='image',
        ),
    ]
