# Generated by Django 3.2.12 on 2022-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_historytranslation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/history/', verbose_name='image'),
        ),
    ]
