# Generated by Django 3.2.12 on 2022-03-16 08:10

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_history_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(default='https://www.youtube.com/embed/iNTj-r3Nq4Q')),
                ('thumbnail', models.ImageField(upload_to='frontend/speech/')),
            ],
            options={
                'verbose_name': 'speech',
                'verbose_name_plural': 'speech',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpeechTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('leader', models.CharField(blank=True, max_length=255, null=True, verbose_name='leader')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='frontend.speech')),
            ],
            options={
                'verbose_name': 'speech Translation',
                'db_table': 'frontend_speech_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
