# Generated by Django 3.2.12 on 2022-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_speech_speechtranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechtranslation',
            name='date',
        ),
        migrations.AddField(
            model_name='speech',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
    ]
