# Generated by Django 3.2.12 on 2022-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20220316_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytranslation',
            name='date',
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
    ]
